<div id="main-container">

    <?php $this->partial('partials/memberHeader'); ?>

    <div id="inner-container">

        <?php echo $this->flash->output() . '<br/>'; ?>

        <div id="controllers">

            <div id="controllers-left">
                <div id="create-application">
                    <?php echo Phalcon\Tag::linkTo(array('applications/create', "Create New Application", 'class' => 'control')) . "\n"; ?>
                </div>
            </div>

            <div id="controllers-right">
                <div id="sorting">
                    <a href="#">Details</a>
                    <a href="#">List</a>
                </div>
                <div id="filter">
                    <a href="#">Some</a>
                    <a href="#">Filters</a>
                </div>
            </div>
        </div> <!-- end #controllers -->

        <div id="applications" class="container">

            <?php

            foreach($applications as $application) {

                $form = new OverviewApplicationForm($application);

                echo $this->partial('partials/overview-application') . "\n";

            }

            ?>

        </div> <!-- end #applications -->

    </div> <!-- end #inner-container -->

</div> <!-- end #main-container -->