<div id="controllers" class="<?php echo $missing_entries_class; ?>">

    <div id="controllers" class="container">
        <div id="create-application">
            <a class="btn btn-primary" href="create"><?php echo $inner_text; ?></a>
        </div>
        <div id="sorting-and-filtering" class="btn-group" role="group">
            <a href="/application/setviewtype" class="<?php echo $view_types->details_classes; ?>"><span><i class="glyphicon glyphicon-th-large"></i></span></a>
            <a href="/application/setviewtype" class="<?php echo $view_types->list_classes; ?>"><span><i class="glyphicon glyphicon-list"></i></span></a>
        </div>
        <button type="button" class="btn btn-default">Filter</button>
    </div>

</div> <!-- end #controllers -->