<!-- Modal -->
<div class="modal" id="contact-modal-create" tabindex="-1" role="dialog" aria-labelledby="contact-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Create New Contact</h4>
            </div>
            <div class="modal-body">

                <!-- start custom content -->

                <form action="/contacts/save" name="contact-modal-create" method="post" role="form">

                    <div class="contact-bottom">

                        <div class="contact-name form-group">
                            <label for="contact-modal-create-name">Name: </label>
                            <input name="contact-modal-create-name" id="contact-modal-create-name" type="text" class="form-control" value="" placeholder="Contact Name" maxlength="50"/>
                        </div>

                        <div class="contact-position form-group">
                            <label for="contact-modal-create-position">Position: </label>
                            <input name="contact-modal-create-name" id="contact-modal-create-position" type="text" class="form-control" value="" placeholder="Contact Position" maxlength="50"/>
                        </div>

                        <div class="contact-email form-group">
                            <label for="contact-modal-create-email">Email: </label>
                            <input name="contact-modal-create-email" id="contact-modal-create-email" type="email" class="form-control" value="" placeholder="Contact Email" maxlength="50"/>
                        </div>

                        <div class="contact-phone form-group">
                            <label for="contact-modal-create-phone">Phone: </label>
                            <input name="contact-modal-create-phone" id="contact-modal-create-phone" type="text" class="form-control" value="" placeholder="Contact Phone" maxlength="50"/>
                        </div>

                        <div class="contact-notes form-group">
                            <label for="contact-modal-create-notes">Notes: </label>
                            <textarea name="contact-modal-create-notes" id="contact-modal-create-notes" value="" class="form-control" placeholder="Contact Notes" maxlength="500"></textarea>
                        </div>

                    </div> <!-- end #contact-bottom -->

                </form>

                <!-- end custom content -->

            </div>

            <div class="modal-footer">
                <button id="exit-contact-modal-create" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="save-contact-modal-create" type="button" class="btn btn-primary">Save Contact</button>
            </div>

        </div>
    </div>
</div>
<!-- end modal -->