<!-- Modal -->
<div class="modal" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="contact-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Create New Contact</h4>
            </div>
            <div class="modal-body">

                <!-- start custom content -->

                <form action="/contacts/save" name="create-contact" method="post" role="form">

                    <div class="contact-bottom">

                        <div class="contact-name form-group">
                            <?php echo $contact_form->label('name') . "\n"; ?>
                            <?php echo $contact_form->render('name') . "\n"; ?>
                        </div>

                        <div class="contact-position form-group">
                            <?php echo $contact_form->label('position') . "\n"; ?>
                            <?php echo $contact_form->render('position') . "\n"; ?>
                        </div>

                        <div class="contact-email form-group">
                            <?php echo $contact_form->label('email') . "\n"; ?>
                            <?php echo $contact_form->render('email') . "\n"; ?>
                        </div>

                        <div class="contact-phone form-group">
                            <?php echo $contact_form->label('phone') . "\n"; ?>
                            <?php echo $contact_form->render('phone') . "\n"; ?>
                        </div>

                        <div class="contact-notes form-group">
                            <?php echo $contact_form->label('notes') . "\n"; ?>
                            <?php echo $contact_form->render('notes') . "\n"; ?>
                        </div>

                    </div> <!-- end #contact-bottom -->

                </form>

                <!-- end custom content -->

            </div>
            <div class="modal-footer">
                <button id="exit-modal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="save-modal" type="button" class="btn btn-primary">Save Contact</button>
            </div>
        </div>
    </div>
</div>