<!-- dialog start -->

<div class="container">

    <dialog id="open-modal" class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

        <div class="modal-top">

            <div class="form-controls">
                <div>
                    <h3>Create New Contact</h3>
                </div>
                <div>
                    <a id="exit-modal" class="btn btn-default btn-sm"><span><i class="glyphicon glyphicon-arrow-left"></i></span></a>
                    <button id="save-modal" type="button" class="btn btn-sm btn-default save-item"><span><i class="glyphicon glyphicon-ok"></i></span> </button>
                </div>
            </div>

        </div>

        <form action="/contacts/save" name="create-contact" method="post" role="form">

            <div class="contact-bottom">

                <div class="contact-name form-group">
                    <?php echo $contact_form->label('name') . "\n"; ?>
                    <?php echo $contact_form->render('name') . "\n"; ?>
                </div>

                <div class="contact-position form-group">
                    <?php echo $contact_form->label('position') . "\n"; ?>
                    <?php echo $contact_form->render('position') . "\n"; ?>
                </div>

                <div class="contact-email form-group">
                    <?php echo $contact_form->label('email') . "\n"; ?>
                    <?php echo $contact_form->render('email') . "\n"; ?>
                </div>

                <div class="contact-phone form-group">
                    <?php echo $contact_form->label('phone') . "\n"; ?>
                    <?php echo $contact_form->render('phone') . "\n"; ?>
                </div>

                <div class="contact-notes form-group">
                    <?php echo $contact_form->label('notes') . "\n"; ?>
                    <?php echo $contact_form->render('notes') . "\n"; ?>
                </div>

            </div> <!-- end #contact-bottom -->

        </form>

    </dialog>

</div>

<!-- dialog end -->