<div class="application-list row">

    <div class="application-start">

        <div class="application-list-date col-md-2">
            <a href="/application/setApplicationOrder?app_order=due" class="application-order-link">Due Date</a>
        </div>

        <div class="application-list-date col-md-2">
            <a href="/application/setApplicationOrder?app_order=applied" class="application-order-link">Applied</a>
        </div>

        <div class="application-list-date col-md-2">
            <a href="/application/setApplicationOrder?app_order=follow_up" class="application-order-link">Follow-Up</a>
        </div>

        <div class="application-list-company col-md-2">
            <a href="/application/setApplicationOrder?app_order=company" class="application-order-link">Company</a>
        </div>

        <div class="application-list-position col-md-2">
            <a href="/application/setApplicationOrder?app_order=position" class="application-order-link">Position</a>
        </div>

        <div class="form-controls col-md-2">
            <!-- placeholder for form-controls column -->
        </div>

    </div>
</div>