
<div class="application col-sm-6 col-xs-12">

    <?php echo Phalcon\Tag::form(array("application/edit", "method" => "post", "name" => "application-form", "role" => "form")) . "\n"; ?>

    <div class="application-top">

        <div class="application-edit">
            <?php echo $form->render('Edit') . "\n"; ?>
        </div>

    </div>

    <div class="application-bottom">

        <div class="application-left col-sm-6 col-xs-12 form-group">

            <div class="application-company">
                <?php echo $form->label('company') . "\n"; ?>
                <?php echo $form->render('company') . "\n"; ?>
            </div>

            <div class="application-position">
                <?php echo $form->label('position') . "\n"; ?>
                <?php echo $form->render('position') . "\n"; ?>
            </div>

            <div class="application-notes">
                <?php echo $form->label('notes') . "\n"; ?>
                <?php echo $form->render('notes') . "\n"; ?>
            </div>

            <div class="application-recruitment">
                <?php echo $form->label('recruitment') . "\n"; ?>
                <?php echo $form->render('recruitment') . "\n"; ?>
            </div>

        </div> <!-- end .application-left -->

        <div class="application-right col-sm-6 col-xs-12">

            <div class="application-applied">
                <?php echo $form->label('applied') . "\n"; ?>
                <?php echo $form->render('applied') . "\n"; ?>
            </div>

            <div class="application-due-date">
                <?php echo $form->label('due_date') . "\n"; ?>
                <?php echo $form->render('due_date') . "\n"; ?>
            </div>

            <div class="application-follow-up">
                <?php echo $form->label('follow_up') . "\n"; ?>
                <?php echo $form->render('follow_up') . "\n"; ?>
            </div>

            <div class="application-contacts">
                <?php

                $html = '';

                $attachments = ContactAttachments::find(array(
                    'conditions' => 'app_id = ?1',
                    'bind' => array(1 => $application->id)
                ));

                if(!count($attachments)) {

                    $html .= '<div>' . "\n";
                    $html .= '<h4>Contacts</h4>' . "\n";
                    $html .= '<p>There are no attached contacts ...</p>' . "\n";
                    $html .= '</div>' . "\n";

                } else {

                    $html .= '<div>' . "\n";
                    $html .= '<h4>Contacts</h4>' . "\n";
                    $html .= '<ul>' . "\n";

                    foreach($attachments as $attachment) {

                        $contact = Contacts::findFirst('id = "' . $attachment->contact_id . '"');

                        $html .= '<li>' . "\n";
                        $html .= '<p>' . "\n";
                        $html .= $contact->name;
                        $html .= '<details>' . "\n";
                        $html .= $contact->email;
                        $html .= '</details>' . "\n";
                        $html .= '</p>' . "\n";
                        $html .= '</li>' . "\n";

                    }

                    $html .= '</ul>' . "\n";
                    $html .= '</div>' . "\n";

                }

                echo $html;

                ?>
            </div>

        </div> <!-- end .application-right -->

    </div> <!-- end .application-bottom -->

    <?php echo Phalcon\Tag::endForm() . "\n"; ?>

</div>