<div class="contact-list row">

    <div class="contact-start">

        <div class="contact-list-name col-xs-4 col-sm-4 col-md-3 col-lg-3">
            <a href="/contacts/setContactsOrder?contacts_order=name" class="contact-order-link">Name</a>
        </div>

        <div class="contact-list-position col-xs-4 col-sm-4 col-md-3 col-lg-3">
            <a href="/contacts/setContactsOrder?contacts_order=position" class="contact-order-link">Position</a>
        </div>

        <div class="contact-list-addresses hidden-xs hidden-sm col-md-3 col-lg-3">
            <div class="contact-list-address xs-hidden hidden-xs hidden-sm col-md-6 col-lg-6">
                Phone
            </div>

            <div class="contact-list-address hidden-xs hidden-sm col-md-6 col-lg-6">
                Email
            </div>
        </div>

        <div class="form-controls col-xs-4 col-sm-4 col-md-3 col-lg-3">
            <!-- placeholder for form-controls column -->
        </div>

    </div>
</div>