
<div class="application-list row">

    <?php echo Phalcon\Tag::form(array("application/edit", "method" => "get", "name" => "application-form", "role" => "form")) . "\n"; ?>

    <div class="application-start">

        <div class="application-list-dates col-xs-2 col-sm-4 col-md-5 col-lg-6">

            <!-- due date -->
            <div class="application-list-date hidden-xs hidden-sm hidden-md col-lg-4">
                <div class="input-group-container">
                    <?php
                    if(strtotime($application->due) < strtotime(date("Y-m-d"))) {
                        echo '<div class="input-group">' . "\n";
                        echo '<span class="input-group-addon overdue-date">!</span>' . "\n";
                        echo '<input type="text" name="applied" value="' . $application->due . '" class="form-control" placeholder="Enter a Date" disabled="disabled" />' . "\n";
                        echo '</div>' . "\n";
                    } else {
                        echo '<div>' . "\n";
                        echo '<input type="text" name="applied" value="' . $application->due . '" class="form-control" placeholder="Enter a Date" disabled="disabled" />' . "\n";
                        echo '</div>' . "\n";
                    }
                    ?>
                </div>
            </div>

            <!-- applied -->
            <div class="application-list-date hidden-xs hidden-sm col-md-6 col-lg-4">
                <div class="input-group-container">
                    <?php
                    if(strtotime($application->applied) < strtotime(date("Y-m-d"))) {
                        echo '<div class="input-group">' . "\n";
                        echo '<span class="input-group-addon overdue-date">!</span>' . "\n";
                        echo '<input type="text" name="applied" value="' . $application->applied . '" class="form-control" placeholder="Enter a Date" disabled="disabled" />' . "\n";
                        echo '</div>' . "\n";
                    } else {
                        echo '<div>' . "\n";
                        echo '<input type="text" name="applied" value="' . $application->applied . '" class="form-control" placeholder="Enter a Date" disabled="disabled" />' . "\n";
                        echo '</div>' . "\n";
                    }
                    ?>
                </div>
            </div>

            <!-- follow-up > xs -->
            <div class="application-list-date hidden-xs col-sm-12 col-md-6 col-lg-4">
                <div class="input-group-container">
                    <?php
                    if(strtotime($application->follow_up) < strtotime(date("Y-m-d"))) {
                        echo '<div class="input-group">' . "\n";
                        echo '<span class="input-group-addon overdue-date">!</span>' . "\n";
                        echo '<input type="text" name="applied" value="' . $application->follow_up . '" class="form-control" placeholder="Enter a Date" disabled="disabled" />' . "\n";
                        echo '</div>' . "\n";
                    } else {
                        echo '<div>' . "\n";
                        echo '<input type="text" name="applied" value="' . $application->follow_up . '" class="form-control" placeholder="Enter a Date" disabled="disabled" />' . "\n";
                        echo '</div>' . "\n";
                    }
                    ?>
                </div>
            </div>

            <!-- follow-up = xs -->
            <div class="application-list-date col-xs-12 hidden-sm hidden-md hidden-lg">

                <?php
                $html = '';
                if(strtotime($application->follow_up) < strtotime(date("Y-m-d"))) {
                    $html .= '<div class="overdue-date">' . "\n";
                } else {
                    $html .= '<div>' . "\n";
                }

                $html .= '<p>' . date("M", strtotime($application->follow_up)) . '</p>' . "\n";
                $html .= '<p>' . date("d", strtotime($application->follow_up)) . '</p>' . "\n";
                $html .= '</div>' . "\n";

                echo $html;
                ?>
            </div>

        </div> <!-- end .application-list-dates -->

        <!-- company; and position (specific element for position on xs) -->
        <div class="application-list-company col-xs-7 col-sm-3 col-md-2 col-lg-2">
            <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <?php echo $application->company . "\n"; ?>
            </div>
            <div class="row col-xs-12 hidden-sm hidden-md hidden-lg">
                <?php echo $application->position . "\n"; ?>
            </div>
        </div>

        <!-- end holder; position (all but xs) and form controllers -->
        <div class="application-list-end-holder col-xs-3 col-sm-5 col-md-5 col-lg-4">

            <!-- position -->
            <div class="application-list-position hidden-xs col-sm-7 col-md-6 col-lg-8">
                <?php echo $application->position . "\n"; ?>
            </div>

            <!-- form controllers -->
            <div class="form-controls col-xs-12 col-sm-5 col-md-6 col-lg-4">
                <input type="hidden" id="app_id" name="app_id" value="<?php echo $application->id . "\n"; ?>"/>
                <div class="buttons">
                    <button type="submit" class="btn btn-sm btn-default edit-item"><span class="glyphicon glyphicon-pencil"></span> </button>
                    <button type="button" class="btn btn-sm btn-default application-overview-delete delete-item"><span class="glyphicon glyphicon-remove"></span></button>
                </div>
            </div>

        </div>

    </div> <!-- end .application-start -->

    <?php echo Phalcon\Tag::endForm() . "\n"; ?>

</div>