
<div class="contact col-xs-12 col-sm-6 col-md-6 col-lg-4">

    <?php echo Phalcon\Tag::form(array("contacts/edit", "method" => "get", "name" => "contact-form", "role" => "form")) . "\n"; ?>

    <div class="contact-top">

        <div class="form-controls">
            <?php echo $form->render('contact_id') . "\n"; ?>

            <div>
                <button type="submit" class="btn btn-sm btn-default edit-item"><span class="glyphicon glyphicon-pencil"></span></button>
                <button type="button" class="btn btn-sm btn-default contact-overview-delete delete-item"><span class="glyphicon glyphicon-remove"></span></button>
            </div>
        </div>

    </div>

    <div class="contact-bottom">

        <div class="contact-name form-group">
            <p>
                <span class="entry-label">Name: </span>
                <span class="entry-value">
                    <?php
                    if(strlen($contact->name) > 0) {
                        echo $contact->name;
                    } else {
                        echo 'Unspecified';
                    }
                    ?>
                </span>
            </p>
        </div>

        <div class="contact-position form-group">
            <p>
                <span class="entry-label">Position: </span>
                <span class="entry-value">
                    <?php
                    if(strlen($contact->position) > 0) {
                        echo $contact->position;
                    } else {
                        echo 'Unspecified';
                    }
                    ?>
                </span>
            </p>
        </div>

        <div class="contact-email form-group">
            <p>
                <span class="entry-label">Email: </span>
                <span class="entry-value">
                    <?php

                    if(strlen($contact->email) > 0) {
                        echo $contact->email;
                    } else {
                        echo 'Unspecified';
                    }

                    ?>
                </span>
            </p>
        </div>

        <div class="contact-phone form-group">
            <p>
                <span class="entry-label">Phone: </span>
                <span class="entry-value">
                    <?php

                    if(strlen($contact->phone) > 0) {
                        echo $contact->phone;
                    } else {
                        echo 'Unspecified';
                    }

                    ?>
                </span>
            </p>
        </div>

        <div class="contact-notes form-group">
            <p>
                <span class="entry-label">Notes: </span>
                <?php

                if(strlen($contact->notes) > 0) {
                    echo '<textarea class="form-controls" disabled="disabled">' . $contact->notes . '</textarea>' . "\n";
                } else {
                    echo '<textarea class="form-controls" disabled="disabled">You haven\'t made any notes yet.</textarea>' . "\n";
                }

                ?>
            </p>
        </div>

    </div>

    <?php echo Phalcon\Tag::endForm() . "\n"; ?>

</div> <!-- end .contact -->