<div class="contact-list row">

    <div class="contact-start">

        <div class="contact-list-name col-xs-5 col-sm-4 col-md-3 col-lg-3">
            <a href="/contacts/setContactsOrder?contacts_order=name" class="contact-order-link">Name</a>
        </div>

        <div class="contact-list-position col-xs-4 col-sm-5 col-md-2 col-lg-2">
            <a href="/contacts/setContactsOrder?contacts_order=position" class="contact-order-link">Position</a>
        </div>

        <div class="contact-list-address hidden-xs hidden-sm col-md-3 col-lg-3">
            Email
        </div>

        <div class="form-controls col-xs-3 col-sm-3 col-md-4 col-lg-4">
            <div class="contact-list-address xs-hidden hidden-xs hidden-sm col-md-6 col-lg-6">
                Phone
            </div>
            <div class="col-log-4">
            <!-- placeholder for form-controls column -->
            </div>
        </div>

    </div>
</div>