<div class="application-list row">

    <div class="application-start container">

        <div class="application-list-dates col-xs-3 col-sm-3 col-md-4 col-lg-5">

            <div class="application-list-date hidden-xs hidden-sm hidden-md col-lg-4">
                <a href="/application/setApplicationOrder?app_order=due" class="application-order-link">Due</a>
            </div>

            <div class="application-list-date hidden-xs hidden-sm col-md-6 col-lg-4">
                <a href="/application/setApplicationOrder?app_order=applied" class="application-order-link">Applied</a>
            </div>

            <div class="application-list-date col-xs-12 col-sm-12 col-md-6 col-lg-4">
                <a href="/application/setApplicationOrder?app_order=follow_up" class="application-order-link hidden-xs">Follow-Up</a>
            </div>

        </div>

        <div class="application-list-company col-xs-5 col-sm-4 col-md-3 col-lg-3">
            <a href="/application/setApplicationOrder?app_order=company" class="application-order-link">Company</a>
        </div>

        <div class="application-list-position hidden-xs col-sm-3 col-md-5 col-lg-4">

            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                <a href="/application/setApplicationOrder?app_order=position" class="application-order-link">Position</a>
            </div>
            <div class="col-xs-4 col-sm-4m col-md-4 col-lg-4">

            </div>
        </div>

    </div>
</div>