<div id="main-container">

    <?php $this->partial('partials/memberHeader'); ?>

    <div id="controllers-placeholder"></div>

    <div id="inner-container">

        <div id="contact" class="container col-md-4 col-md-offset-4">

            <?php echo Phalcon\Tag::form(array("contacts/save", "method" => "post", "name" => "create-contact", "role" => "form")) . "\n"; ?>

            <div class="contact-top">

                <div class="form-controls">
                    <div>
                        <a class="btn btn-default btn-sm cancel-item" href="/contacts/cancel"><span class="glyphicon glyphicon-arrow-left"></span></a>
                        <button type="submit" class="btn btn-sm btn-default save-item"><span class="glyphicon glyphicon-ok"></span></button>
                    </div>
                </div>

            </div> <!-- end #contact-top -->

            <div class="contact-bottom">

                <div class="contact-name form-group">
                    <?php echo $form->label('name') . "\n"; ?>
                    <?php echo $form->render('name') . "\n"; ?>
                </div>

                <div class="contact-position form-group">
                    <?php echo $form->label('position') . "\n"; ?>
                    <?php echo $form->render('position') . "\n"; ?>
                </div>

                <div class="contact-email form-group">
                    <?php echo $form->label('email') . "\n"; ?>
                    <?php echo $form->render('email') . "\n"; ?>
                </div>

                <div class="contact-phone form-group">
                    <?php echo $form->label('phone') . "\n"; ?>
                    <?php echo $form->render('phone') . "\n"; ?>
                </div>

                <div class="contact-notes form-group">
                    <?php echo $form->label('notes') . "\n"; ?>
                    <?php echo $form->render('notes') . "\n"; ?>
                </div>

            </div> <!-- end #contact-bottom -->

            <?php echo Phalcon\Tag::endForm() . "\n"; ?>

        </div> <!-- end #contact -->

    </div> <!-- end #inner-container -->

</div> <!-- end #main-container -->