<div id="main-container">

    <?php $this->partial('partials/memberHeader'); ?>

    <div id="inner-container">

        <?php echo $this->flash->output() . '<br/>'; ?>

        <?php echo $this->partial('partials/controllers-template') . "\n"; ?>

        <div id="contacts" class="container">

            <?php

            foreach($contacts as $contact) {

                $form = new OverviewContactForm($contact);

                echo $this->partial('partials/overview-contact-template') . "\n";

            }

            ?>

        </div> <!-- end #contacts -->

    </div> <!-- end #inner-container -->

</div> <!-- end #main-container -->