<div id="main-container">

    <div id="dialog-overlay"></div>

    <?php $this->partial('partials/memberHeader'); ?>

    <div id="inner-container">

        <div id="application" class="container col-md-6 col-md-offset-3">

            <?php echo Phalcon\Tag::form(array("application/save", "method" => "post", "name" => "create-application", "role" => "form")) . "\n"; ?>

            <div class="application-top">

                <div class="form-controls">
                    <div>
                        <a class="btn btn-default btn-sm cancel-item" href="/application/cancel"><i class="glyphicon glyphicon-arrow-left"></i></span></a>
                        <button id="save-application" type="button" class="btn btn-sm btn-default save-item"><span><i class="glyphicon glyphicon-ok"></i></span> </button>
                    </div>
                </div>

            </div> <!-- end #application-top -->

            <div class="application-bottom row">

                <div class="application-left col-xs-12 col-sm-12 col-md-6 col-lg-6">

                    <div class="application-company form-group">
                        <?php echo $application_form->label('company') . "\n"; ?>
                        <?php echo $application_form->render('company') . "\n"; ?>
                    </div>

                    <div class="application-position form-group">
                        <?php echo $application_form->label('position') . "\n"; ?>
                        <?php echo $application_form->render('position') . "\n"; ?>
                    </div>

                    <div class="application-recruitment application_form-group">
                        <?php echo $application_form->label('recruitment') . "\n"; ?>
                        <?php echo $application_form->render('recruitment') . "\n"; ?>
                    </div>

                    <div class="application-notes application_form-group">
                        <?php echo $application_form->label('notes') . "\n"; ?>
                        <?php echo $application_form->render('notes') . "\n"; ?>
                    </div>

                </div> <!-- end .application-left -->

                <div class="application-right col-xs-12 col-sm-12 col-md-6 col-lg-6">

                    <div class="application-applied application_form-group">
                        <?php echo $application_form->label('applied') . "\n"; ?>
                        <?php echo $application_form->render('applied') . "\n"; ?>
                    </div>

                    <div class="application-due-date application_form-group">
                        <?php echo $application_form->label('due_date') . "\n"; ?>
                        <?php echo $application_form->render('due_date') . "\n"; ?>
                    </div>

                    <div class="application-follow-up application_form-group">
                        <?php echo $application_form->label('follow_up') . "\n"; ?>
                        <?php echo $application_form->render('follow_up') . "\n"; ?>
                    </div>

                    <div class="application-attachments-form form-group">
                        <label>Add Contact:</label>
                        <select id="select-contact" class="form-control">
                            <option value="-1">Select a Contact</option>
                            <option value="0">Create New Contact</option>

                            <?php

                            $html = '';

                            foreach($contacts as $contact) {

                                $html .= '<option value="' . $contact->id . '">' . $contact->name . '</option>' . "\n";

                            }

                            echo $html;

                            ?>

                        </select>

                    </div>

                    <div class="application-attachments form-group">
                        <label>Contacts:</label>
                        <ul id="contacts-list">
                        </ul>
                    </div>

                </div> <!-- end .application-right -->

            </div> <!-- end #application-bottom -->

            <?php echo Phalcon\Tag::endForm() . "\n"; ?>

        </div> <!-- end #application -->

    </div> <!-- end #inner-container -->

</div> <!-- end #main-container -->