<?php $this->partial('partials/memberHeader'); ?>
<div id="main-container">

    <div id="inner-container">

        <?php echo Phalcon\Tag::form(array("application/save", "method" => "post", "name" => "save-application")) . "\n"; ?>

        <?php echo $form->label('company') . "\n"; ?>
        <?php echo $form->render('company') . "\n"; ?>

        <?php echo $form->label('position') . "\n"; ?>
        <?php echo $form->render('position') . "\n"; ?>

        <?php echo $form->label('recruitment') . "\n"; ?>
        <?php echo $form->render('recruitment') . "\n"; ?>

        <?php echo $form->label('notes') . "\n"; ?>
        <?php echo $form->render('notes') . "\n"; ?>

        <?php echo $form->label('applied') . "\n"; ?>
        <?php echo $form->render('applied') . "\n"; ?>

        <?php echo $form->label('due_date') . "\n"; ?>
        <?php echo $form->render('due_date') . "\n"; ?>

        <?php echo $form->label('follow_up') . "\n"; ?>
        <?php echo $form->render('follow_up') . "\n"; ?>

        <div class="form-controls">
            <?php echo $form->render('Save Application') . "\n"; ?>
            <?php echo Phalcon\Tag::linkTo(array("application/cancel", "Cancel", "class" => "btn btn-danger")) . "\n"; ?>
        </div>

        <?php echo Phalcon\Tag::endForm() . "\n"; ?>

    </div> <!-- end #inner-container -->

</div> <!-- end #main-container -->