<?php $this->partial('partials/memberHeader'); ?>
<div id="main-container">

    <div id="inner-container">

        <div id="application" class="container col-md-6 col-md-offset-3">

            <?php echo Phalcon\Tag::form(array("application/save", "method" => "post", "name" => "application-form", "role" => "form")) . "\n"; ?>

            <div class="application-top">

                <div class="form-controls">
                    <div>
                        <a class="btn btn-default btn-sm cancel-item" href="/application/cancel"><i class="glyphicon glyphicon-arrow-left"></i></span></a>
                        <button id="save-application" type="button" class="btn btn-sm btn-default save-item"><span><i class="glyphicon glyphicon-ok"></i></span> </button>
                        <button id="application-delete" type="button" class="btn btn-sm btn-default delete-item"><span><i class="glyphicon glyphicon-remove"></i></span> </button>
                    </div>
                </div>

            </div>

            <div class="application-bottom row">

                <div class="application-left form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">

                    <div class="application-company form-group">
                        <?php echo $form->label('company') . "\n"; ?>
                        <?php echo $form->render('company') . "\n"; ?>
                    </div>

                    <div class="application-position form-group">
                        <?php echo $form->label('position') . "\n"; ?>
                        <?php echo $form->render('position') . "\n"; ?>
                    </div>

                    <div class="application-recruitment form-group">
                        <?php echo $form->label('recruitment') . "\n"; ?>
                        <?php echo $form->render('recruitment') . "\n"; ?>
                    </div>

                    <div class="application-notes form-group">
                        <?php echo $form->label('notes') . "\n"; ?>
                        <?php echo $form->render('notes') . "\n"; ?>
                    </div>

                    <?php echo $form->render('app_id') . "\n"; ?>

                </div> <!-- end .application-left -->

                <div class="application-right col-xs-12 col-sm-12 col-md-6 col-lg-6">

                    <div class="application-applied form-group">
                        <?php echo $form->label('applied') . "\n"; ?>
                        <?php echo $form->render('applied') . "\n"; ?>
                    </div>

                    <div class="application-due-date form-group">
                        <?php echo $form->label('due_date') . "\n"; ?>
                        <?php echo $form->render('due_date') . "\n"; ?>
                    </div>

                    <div class="application-follow-up form-group">
                        <?php echo $form->label('follow_up') . "\n"; ?>
                        <?php echo $form->render('follow_up') . "\n"; ?>
                    </div>

                    <div class="application-attachments-form form-group">
                        <label>Add Contact:</label>
                        <select id="select-contact" class="form-control">
                            <option value="-1">Select a Contact</option>
                            <option value="0">Create New Contact</option>

                            <?php

                            $html = '';

                            foreach($contacts as $contact) {

                                $html .= '<option value="' . $contact->id . '">' . $contact->name . '</option>' . "\n";

                            }

                            echo $html;

                            ?>

                        </select>
                    </div>

                    <div class="application-attachments form-group">
                        <label>Contacts:</label>
                        <ul id="contacts-list">
                            <!-- placeholder for contacts attached to the application -->
                            <?php

                            $attachments = ContactAttachments::find(array(
                                'conditions' => 'app_id = ?1',
                                'bind' => array(1 => $application->id)
                            ));

                            $html = '';

                            foreach($attachments as $attachment) {

                                $contact = Contacts::findFirst('id = "' . $attachment->contact_id . '"');

                                $html .= '<li class="bg-success">';
                                $html .= '<div>';
                                $html .= '<input type="hidden" value="' . $contact->id . '"/>';
                                $html .= '<span class="contact-name">';
                                $html .= '<a class="attachment-details">' . $contact->name . '</a>';

                                if(strlen($contact->position) > 0) {
                                    $html .= '<br>';
                                    $html .= '<span class="hidden-xs">';
                                    $html .= '(' . $contact->position . ')';
                                    $html .= '</span>';
                                }

                                $html .= '</span>';
                                $html .= '</div>';

                                $html .= '<div>' . "\n";
                                $html .= '<button class="btn btn-danger btn-xs contact-remove" type="button">remove</button>' . "\n";
                                $html .= '</div>' . "\n";

                                $html .= '</li>';

                            }

                            echo $html;

                            ?>
                        </ul>
                    </div>

                </div> <!-- end .application-right -->

            </div> <!-- end .application-bottom -->

            <?php echo Phalcon\Tag::endForm() . "\n"; ?>

        </div>

    </div> <!-- end #inner-container -->

</div> <!-- end #main-container -->
