
<div id="main-container">

    <?php $this->partial('partials/memberHeader'); ?>

    <div id="inner-container">

        <?php echo $this->flash->output() . '<br/>'; ?>

        <?php echo $this->partial('partials/controllers-template') . "\n"; ?>

        <div id="applications" class="container">

            <?php

            if(count($applications) > 0) {

                if($user->view_type == "OVERVIEW") {

                    $counter = 0;

                    foreach($applications as $application) {

                        if($counter % 2 == 0) {
                            echo '<div class="application-row row">' . "\n";
                        }

                        if($user->view_type == "OVERVIEW") {
                            echo $this->partial('partials/overview-application-details-template') . "\n";
                        } else {
                            echo $this->partial('partials/overview-application-list-template') . "\n";
                        }

                        if($counter % 2 == 1 || $counter + 1 == count($applications)) {
                            echo '</div> <!-- end .application-row -->' . "\n";
                        }

                        $counter++;

                    }

                } else {

                    echo '<div class="container">' . "\n";
                    echo $this->partial('partials/overview-application-list-headers') . "\n";

                    foreach($applications as $application) {

                        if($user->view_type == "OVERVIEW") {
                            echo $this->partial('partials/application-template') . "\n";
                        } else {
                            echo $this->partial('partials/overview-application-list-template') . "\n";
                        }

                    }

                    echo '</div>' . "\n";

                }

            } else {

                echo $this->partial('partials/missing-entries') . "\n";

            }

            ?>

            <?php echo $this->partial('partials/contact-modal-presentation') . "\n"; ?>

        </div> <!-- end #applications -->

    </div> <!-- end #inner-container -->

</div> <!-- end #main-container -->